name: Release Send!

on:
  push:
    tags:
      - "*"

jobs:
  ReleaseCI:
    runs-on: macos-latest

    steps:
    - name: Checkout 🚚
      uses: actions/checkout@v3

    - name: Install Dependencies 🚀
      run: brew install create-dmg
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Install latest stable Rust toolchain 🦀
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
          override: true

    - name: Release Build 🔨
      run: |
        xcodebuild -scheme Send -configuration Release -derivedDataPath build -disableAutomaticPackageResolution CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

    - name: Create Disk Image 💿
      run: |
        XCBUILD_PATH="build/Build/Products/Release"
        cd -
        cp ./dmg/dmg-background.tiff $XCBUILD_PATH
        cp ./dmg/dmg-VolumeIcon.icns $XCBUILD_PATH
        cd $XCBUILD_PATH
        create-dmg \
          --volname "Send" \
          --volicon "VolumeIcon.icns" \
          --background "dmg-background.tiff" \
          --window-pos 200 120 \
          --window-size 660 420 \
          --text-size 12 \
          --icon-size 160 \
          --icon "Send.app" 180 170 \
          --hide-extension "Send.app" \
          --app-drop-link 480 170 \
          "Send.dmg" \
          "./Send.app"
        cd -
        mkdir Artifacts
        cp -R ${XCBUILD_PATH}/*.dmg Artifacts
        cd $XCBUILD_PATH
        zip -r Send.zip ./Send.app
        cd -
        cp ${XCBUILD_PATH}/*.zip Artifacts

    - name: Publish GitHub Release 📂
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        prerelease: ${{ env.IS_PRE }}
        artifacts: "./Artifacts/*"
        tag: ${{ env.REL_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}